### ISSUE TITLE
implement SEO best practices

### ISSUE THREAD

**Issue by aniloli42** [Alitindrawan24/2048#25]
I would like to improve the overall score of the site as much as possible.

![image](https://github.com/Alitindrawan24/2048/assets/44222164/41dcb64f-5762-4a01-8107-df8b347d9766)

**Comment by aniloli42** [comment]
Additionally, I will add meta and open graph tags, giving a professional look while sharing the link.

**Comment by Alitindrawan24** [comment]
@aniloli42 I will assign this issue to you
