### ISSUE TITLE
Add info box for controls

### ISSUE THREAD

**Issue by ewatch** [Alitindrawan24/2048#4]
Hey,

I would like to add an info box for controls and probably add the rules for people that play the game for the first time.
What do you think ?

Best regards,
ewatch

**Comment by Alitindrawan24** [comment]
> Hey,
> 
> I would like to add an info box for controls and probably add the rules for people that play the game for the first time. What do you think ?
> 
> Best regards, ewatch

I think this issue has been solved now, Thanks
