### ISSUE TITLE
Change the CSS styling of the webpage

### ISSUE THREAD

**Issue by barunipriyats** [Alitindrawan24/2048#7]
Hi @Alitindrawan24 I would like to change the CSS styling of the webpage by making the page attractive to the user. I am good in this kind of issue. Please assign this task to me. Thank you.

**Comment by Alitindrawan24** [comment]
> Hi @Alitindrawan24 I would like to change the CSS styling of the webpage by making the page attractive to the user. I am good in this kind of issue. Please assign this task to me. Thank you.

Yes but I think the current UI is good, but for sure you can improve the styling and the responsiveness if you want to fix it. Thanks

**Comment by barunipriyats** [comment]
Sure @Alitindrawan24 I will fix it.

**Comment by rafaelaqueirozg** [comment]
Hi @Alitindrawan24, I saw that this issue has been stopped for a long time. 
Can I work on it? If so, can you assign it to me?

**Comment by Alitindrawan24** [comment]
Hi @rafaelaqueirozg Yes of course you can work on it

**Comment by rafaelaqueirozg** [comment]
Hey, @Alitindrawan24. I made some style changes and before I submit them, I would like to get your opinion about.

What do you think? Do you have any suggestions?

![Captura de tela de 2022-10-09 01-09-19](https://user-images.githubusercontent.com/42815135/194737581-3a6b53de-13fb-4512-af34-1143d7f938dc.png)

![Captura de tela de 2022-10-09 01-08-37](https://user-images.githubusercontent.com/42815135/194737577-673e0648-e93f-45ef-a82f-61686ec6b3e8.png)

![Captura de tela de 2022-10-09 01-08-48](https://user-images.githubusercontent.com/42815135/194737578-f99ec5e6-d980-423d-99bc-5b6b0da79881.png)

![Captura de tela de 2022-10-09 01-08-25](https://user-images.githubusercontent.com/42815135/194737575-b7e8f5c3-7092-446a-aae2-1a76eb8171a1.png)

![Captura de tela de 2022-10-09 01-09-15](https://user-images.githubusercontent.com/42815135/194737580-605157cb-50d6-4cba-ae57-7d00020a44df.png)

![Captura de tela de 2022-10-09 01-09-06](https://user-images.githubusercontent.com/42815135/194737579-5e7a4455-bfed-4a15-b972-d3c065dee6f9.png)

**Comment by Alitindrawan24** [comment]
@rafaelaqueirozg What a great UI, I loved it and it is responsive too ? If yes you can make a PR for this update

**Comment by rafaelaqueirozg** [comment]
Sure!! I was applying the responsive details. I'm gonna make a PR for it :)

![image](https://user-images.githubusercontent.com/42815135/194780558-01211362-e1dc-46e3-8e66-ea726bd7a479.png)
